services:

  postgres:
    image: postgres:16.2
    env_file: env/dev.env
    ports:
      - 15432:5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 10s
      retries: 5
      start_period: 30s
    shm_size: "8g"
    sysctls:
      kernel.shmmax: 8589934592
      kernel.shmall: 2097152
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "12g"
        reservations:
          cpus: "4.0"
          memory: "12g"
    #command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
      - ./data/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    #  - ./conf/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - jump_sharding-network

  pgadmin:
    image: dpage/pgadmin4:8.5
    env_file: env/dev.env
    ports:
      - "16543:80"
    volumes:
      - ./conf/pgadmin/servers.json:/pgadmin4/servers.json
    restart: always
    networks:
      - jump_sharding-network
    depends_on:
      postgres:
        condition: service_healthy

  schemaspy:
    image: schemaspy/schemaspy:6.2.4
    platform: linux/amd64
    env_file: env/dev.env
    volumes:
      # - ./experimentos/00-as-is/schemaspy/output:/output
      # - ./experimentos/00-as-is/schemaspy.properties:/schemaspy.properties
      # - ./experimentos/01-particionamento-por-intervalo/schemaspy/output:/output
      # - ./experimentos/01-particionamento-por-intervalo/schemaspy.properties:/schemaspy.properties
      # - ./experimentos/02-particionamento-por-hash/schemaspy/output:/output
      # - ./experimentos/02-particionamento-por-hash/schemaspy.properties:/schemaspy.properties
      - ./experimentos/03-particionamento-hibrido-01/schemaspy/output:/output
      - ./experimentos/03-particionamento-hibrido-01/schemaspy.properties:/schemaspy.properties
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - jump_sharding-network

networks: 
  jump_sharding-network:
    driver: bridge
    attachable: true
